[package]
name = "dagrs"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4.5"
lazy_static = "1.4.0"
bimap = "0.6.1"
deno_core = "0.121.0"
log = "0.4.14"
simplelog = "0.12.0"
clap = { version = "3.0.14", features = ["derive"] }
anymap = "1.0.0-beta.2"
crossbeam = "0.8.1"
thiserror = "1.0.30"
tokio = { version = "1.18", features = ["rt", "rt-multi-thread"] }